version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/my-app
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
